apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
  annotations:
    cert-manager.io/inject-ca-from: webhook/webhook-selfsigned-ca
webhooks:
- name: webhook.example.com
  clientConfig:
    service:
      namespace: "webhook"
      name: "webhook"
      path: "/mutate--v1-pod"
#    caBundle: <CA_BUNDLE>
  timeoutSeconds: 5
  sideEffects: None
  admissionReviewVersions: [ "v1" ]
# failurePolicy: Ignore
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
