apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-selfsigned-ca
  namespace: webhook
spec:
  # isCA: true
  # commonName: webhook-selfsigned-ca
  commonName: webhook.webhook.svc
  secretName: webhook-certificates
  dnsNames:
  - webhook.webhook.svc
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-ca-issuer
  namespace: webhook
spec:
  ca:
    secretName: webhook-certificates
